steps:
# Build the trainer image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/test-servers-349208/mlops:latest', '.']
  
  
# Compile the pipeline
- name: 'gcr.io/$PROJECT_ID/kfp-cli'
  args:
  - '-c'
  - |
    dsl-compile --py pipeline.py --output pipeline.yaml
  
  
 # Upload the pipeline
- name: 'gcr.io/test-servers-349208/mlops'
  args:
  - '-c'
  - |
    kfp --endpoint $_ENDPOINT pipeline upload -p farmer_mlops pipeline.yaml
  


# Push the images to Container Registry 
images: ['gcr.io/test-servers-349208/mlops:latest']
